site_name: Dharma
site_url: https://acorn23.github.io/dharma/
nav:
  - Home: index.md
  - General:
      - Beauty: beauty.md
      - Understanding Reality: reality.md
      - Superstition: superstition.md
      - Death: death.md
      - Dead Internet Theory: dead_internet_theory.md
      - Crypto currency: mining_monero.md
  - Science:
      - Space: space.md
  - AI:
      - AI Governing Humans: ai.md 
  - Geopolitics:
      - Global:
          - Ukraine War: ukraine.md
          - Gaza Genocide: gaza.md
          - USA: USA.md
          - Iran War: iran.md
      - India:
          - Withering Democracy: autocracy.md
          - Global Relations: india.md
          - Financial System: finance.md
  - Archive:
      - The Sacrificial Machine—How Private Finance Turned War into Permanent Profit: war.md 
  - Resources: resources.md
  - About: about.md

theme:
  name: material
  palette:
    primary: deep purple
  logo: img/atom.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
plugins:
  - blog
markdown_extensions:
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
