site_name: Dharma
site_url: https://acorn23.github.io/dharma/

nav:
  - Home: index.md

  - Philosophy:
      - Introduction: introduction.md
      - Understanding Reality: reality.md
      - Death and Morality: death.md
      - Superstition and Belief Systems: superstition.md
      - Postmodernism: postmodernism.md
      - Beauty: beauty.md

  - The Surveillance Apparatus:
      - You are a Commodity: panopticon.md
      - AI Enabled Mass Surveillance: ai.md

  - Geopolitics:
      - Ukraine War: ukraine.md
      - Gaza Genocide: gaza.md
      - India:
          - Withering Democracy: autocracy.md
          - Financial System: finance.md

  - Archive:
      - The Sacrificial Machine—How Private Finance Turned War into Permanent Profit: war.md

  - Resources: resources.md
  - About: about.md

theme:
  name: material

  palette:
    scheme: slate
    primary: teal
    accent: teal

  logo: img/atom.png
  favicon: img/atom.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
    - search.suggest

plugins:
  - blog
  - tags
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

extra_javascript:
  - javascripts/homepage.js
